//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class defense_stats
    {
        public string eid_playerid { get; set; }
        public string playerid { get; set; }
        public string name { get; set; }
        public string tkl { get; set; }
        public string ast { get; set; }
        public string sk { get; set; }
        public string @int { get; set; }
        public string ffum { get; set; }
        public string home_or_away { get; set; }
    }
}
