//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class drive_play_player
    {
        public string eid { get; set; }
        public Nullable<int> drivenum { get; set; }
        public Nullable<int> playnum { get; set; }
        public string playerid { get; set; }
        public Nullable<int> sequence { get; set; }
        public string clubcode { get; set; }
        public string playerName { get; set; }
        public Nullable<int> statId { get; set; }
        public Nullable<int> yards { get; set; }
    }
}
