//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class drive
    {
        public string eid { get; set; }
        public string drivenumber { get; set; }
        public string posteam { get; set; }
        public Nullable<int> qtr { get; set; }
        public string redzone { get; set; }
        public Nullable<int> fds { get; set; }
        public string result { get; set; }
        public Nullable<int> penyds { get; set; }
        public Nullable<int> ydsgained { get; set; }
        public Nullable<int> numplays { get; set; }
        public string postime { get; set; }
        public string start_qtr { get; set; }
        public string start_time { get; set; }
        public string start_yrdln { get; set; }
        public string start_team { get; set; }
        public string end_qtr { get; set; }
        public string end_time { get; set; }
        public string end_yrdln { get; set; }
        public string end_team { get; set; }
    }
}
