//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class drive_play_players
    {
        public string eid_drive_play_playerid_sequence { get; set; }
        public string drivenum { get; set; }
        public string playnum { get; set; }
        public string playerid { get; set; }
        public string sequence { get; set; }
        public string clubcode { get; set; }
        public string playerName { get; set; }
        public string statId { get; set; }
        public string yards { get; set; }
    }
}
