//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class drive_plays
    {
        public string eid_drivenum_playnum { get; set; }
        public string drive_num { get; set; }
        public string playnum { get; set; }
        public string sp { get; set; }
        public string qtr { get; set; }
        public string down { get; set; }
        public string time { get; set; }
        public string yrdln { get; set; }
        public string ydstogo { get; set; }
        public string ydsnet { get; set; }
        public string posteam { get; set; }
        public string desc { get; set; }
        public string note { get; set; }
    }
}
