//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class fumbles_stats
    {
        public string eid_playerid { get; set; }
        public string playerid { get; set; }
        public string name { get; set; }
        public string tot { get; set; }
        public string rcv { get; set; }
        public string trcv { get; set; }
        public string yds { get; set; }
        public string lost { get; set; }
        public string home_or_away { get; set; }
    }
}
