//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_schedule
    {
        public int eid { get; set; }
        public string gsis { get; set; }
        public string day { get; set; }
        public string time { get; set; }
        public string q { get; set; }
        public string k { get; set; }
        public string hometeamabbv { get; set; }
        public string hometeamname { get; set; }
        public string hs { get; set; }
        public string visitingteamabbv { get; set; }
        public string visitingteamname { get; set; }
        public string vs { get; set; }
        public string p { get; set; }
        public string rz { get; set; }
        public string ga { get; set; }
        public Nullable<decimal> season { get; set; }
        public string seasontype { get; set; }
        public Nullable<decimal> week { get; set; }
    }
}
