//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Root> Roots { get; set; }
        public virtual DbSet<drive> drives { get; set; }
        public virtual DbSet<away_team> away_team { get; set; }
        public virtual DbSet<home_team> home_team { get; set; }
        public virtual DbSet<passing_stats> passing_stats { get; set; }
        public virtual DbSet<rushing_stats> rushing_stats { get; set; }
        public virtual DbSet<receiving_stats> receiving_stats { get; set; }
        public virtual DbSet<fumbles_stats> fumbles_stats { get; set; }
        public virtual DbSet<kicking_stats> kicking_stats { get; set; }
        public virtual DbSet<punting_stats> punting_stats { get; set; }
        public virtual DbSet<kickret_stats> kickret_stats { get; set; }
    }
}
