//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class home_team
    {
        public string eid { get; set; }
        public string abbr { get; set; }
        public string team_to { get; set; }
        public string players { get; set; }
        public string score_1 { get; set; }
        public string score_2 { get; set; }
        public string score_3 { get; set; }
        public string score_4 { get; set; }
        public string score_5 { get; set; }
        public string score_t { get; set; }
    }
}
