//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class kicking_stats
    {
        public string eid_playerid { get; set; }
        public string playerid { get; set; }
        public string name { get; set; }
        public string fgm { get; set; }
        public string fga { get; set; }
        public string fgyds { get; set; }
        public string totpfg { get; set; }
        public string xpmade { get; set; }
        public string xpmissed { get; set; }
        public string xpa { get; set; }
        public string xpb { get; set; }
        public string xptot { get; set; }
        public string home_or_away { get; set; }
    }
}
