//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class play
    {
        public string eid { get; set; }
        public Nullable<int> drive_num { get; set; }
        public Nullable<int> playnum { get; set; }
        public Nullable<int> sp { get; set; }
        public Nullable<int> qtr { get; set; }
        public Nullable<int> down { get; set; }
        public string time { get; set; }
        public string yrdln { get; set; }
        public Nullable<int> ydstogo { get; set; }
        public Nullable<int> ydsnet { get; set; }
        public string posteam { get; set; }
        public string desc { get; set; }
        public string note { get; set; }
    }
}
