//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class receiving_stats
    {
        public string eid_playerid { get; set; }
        public string playerid { get; set; }
        public string name { get; set; }
        public string rec { get; set; }
        public string yds { get; set; }
        public string tds { get; set; }
        public string lng { get; set; }
        public string lngtd { get; set; }
        public string twopta { get; set; }
        public string twoptm { get; set; }
        public string home_or_away { get; set; }
    }
}
