//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class Root
    {
        public string eid { get; set; }
        public string weather { get; set; }
        public string media { get; set; }
        public string yl { get; set; }
        public string qtr { get; set; }
        public string note { get; set; }
        public string down { get; set; }
        public string togo { get; set; }
        public string redzone { get; set; }
        public string clock { get; set; }
        public string posteam { get; set; }
        public string stadium { get; set; }
    }
}
