//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class scrsummary_data
    {
        public string eid_scrid { get; set; }
        public string scr_id { get; set; }
        public string type { get; set; }
        public string desc { get; set; }
        public string qtr { get; set; }
        public string team { get; set; }
        public string players { get; set; }
    }
}
