//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class stats_team
    {
        public string eid { get; set; }
        public string team { get; set; }
        public Nullable<decimal> totfd { get; set; }
        public Nullable<decimal> totyds { get; set; }
        public Nullable<decimal> pyds { get; set; }
        public Nullable<decimal> ryds { get; set; }
        public Nullable<decimal> pen { get; set; }
        public Nullable<decimal> penyds { get; set; }
        public Nullable<decimal> trnovr { get; set; }
        public Nullable<decimal> pt { get; set; }
        public Nullable<decimal> ptyds { get; set; }
        public Nullable<decimal> ptavg { get; set; }
        public string top { get; set; }
    }
}
