//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class stats_defense
    {
        public string eid { get; set; }
        public string id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> tkl { get; set; }
        public Nullable<decimal> ast { get; set; }
        public Nullable<decimal> sk { get; set; }
        public Nullable<decimal> @int { get; set; }
        public Nullable<decimal> ffum { get; set; }
    }
}
