//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class team_stats
    {
        public string eid { get; set; }
        public string team_abbr { get; set; }
        public string totfd { get; set; }
        public string totyds { get; set; }
        public string pyds { get; set; }
        public string ryds { get; set; }
        public string pen { get; set; }
        public string penyds { get; set; }
        public string trnovr { get; set; }
        public string pt { get; set; }
        public string ptyds { get; set; }
        public string ptavg { get; set; }
        public string top { get; set; }
        public string home_or_away { get; set; }
    }
}
